language: python

php:
  - 2.7

before_script:
  - pip install -r src/requirements.txt
  - cp src/config/databases.py.sample src/config/databases.py
  - mysql -u root < src/data/sql/mysql_createdb.sql
  - mysql -u root vimman < src/data/sql/mysql_schema.sql

script:
  - python -m unittest discover -s tests/ -p '*_test.py'

notifications:
  email:
    recipients: project.omosan+vimman@gmail.com
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
