language: python
python:
  - 2.7.9
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls
before_script:
  - mysql -u root < data/sql/mysql_createdb.sql
  - mysql -u root vimman < data/sql/mysql_schema.sql
script:
  - flake8 . --exclude=__init__.py,run.py --max-line-length=120
  - python -m unittest discover -s tests/ -p '*_test.py'
  - coverage run --source=src setup.py test
after_success:
  - coveralls
deploy:
  provider: heroku
  app: vimman-api
  api_key: $HEROKU_API_KEY
  on:
    repo: OMOSAN/vimman-api
notifications:
  email:
    recipients: project.omosan+vimman-api@gmail.com
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
env:
  global:
    - DATABASE_URL="mysql://root:@localhost:3306/vimman?charset=utf8&use_unicode=1"
